sites:
  - name: "PokeRogue"
    sitemap_urls:
      - "https://pokerogue.io/sitemap.xml"
    active: true
  - name: "Wordle2"
    sitemap_urls:
      - "https://wordle2.io/sitemap.xml"
    active: true
  - name: "1Games"
    sitemap_urls:
      - "https://1games.io/sitemap.xml"
    active: true
  - name: "AZGames"
    sitemap_urls:
      - "https://azgames.io/sitemap.xml"
    active: true
  - name: "CookieClicker2"
    sitemap_urls:
      - "https://cookie-clicker2.com/sitemap.xml"
    active: true
  - name: "Phrazle"
    sitemap_urls:
      - "https://phrazle.io/sitemap.xml"
    active: true
  - name: "Sprunki"
    sitemap_urls:
      - "https://sprunki.org/sitemap.xml"
    active: true
  - name: "ThatsNotMyNeighbor"
    sitemap_urls:
      - "https://thatsnot-myneighbor.io/sitemap.xml"
    active: true
  - name: "GeometryDashWave"
    sitemap_urls:
      - "https://geometrydashwave.io/sitemap.xml"
    active: true
  - name: "SmashyRoad"
    sitemap_urls:
      - "https://smashy-road.io/sitemap.xml"
    active: true
  - name: "GeometryDashIO"
    sitemap_urls:
      - "https://geometrylite.io/sitemap.xml"
    active: true
  - name: "PizzaEdition"
    sitemap_urls:
      - "https://pizzaedition.win/sitemap.xml"
    active: true
  - name: "EscapeRoad2"
    sitemap_urls:
      - "https://escaperoad2.io/sitemap.xml"
    active: true
  - name: "CoolMathGames"
    sitemap_urls:
      - "https://www.coolmathgames.com/sitemap.xml"
    active: true
  - name: "GameDistribution"
    sitemap_urls:
      - "https://gamedistribution.com/sitemap-index.xml"
    active: true
  - name: "CrazyGames"
    sitemap_urls:
      - "https://www.crazygames.com/sitemap-index.xml"
    active: true
  - name: "Poki"
    sitemap_urls:
      - "https://poki.com/en/sitemaps/index.xml"
    active: true
  - name: "TwoPlayerGames"
    sitemap_urls:
      - "https://www.twoplayergames.org/sitemap-games.xml"
    active: true
  - name: "OnlineGames"
    sitemap_urls:
      - "https://www.onlinegames.io/sitemap.xml"
    active: true
  - name: "MiniPlay"
    sitemap_urls:
      - "https://www.miniplay.com/sitemap.xml"
    active: true
  - name: "SayGames"
    sitemap_urls:
      - "https://say.games/sitemap.xml"
    active: true
  - name: "FreeOnlineGames"
    sitemap_urls:
      - "https://www.freeonlinegames.com/sitemap.xml"
    active: true
  - name: "AddictingGames"
    sitemap_urls:
      - "https://www.addictinggames.com/sitemap.xml"
    active: true
  - name: "GameMonetize"
    sitemap_urls:
      - "https://gamemonetize.com/sitemap.xml"
    active: true
  - name: "GeometryLite"
    sitemap_urls:
      - "https://geometry-lite.io/sitemap.xml"
    active: true
  - name: "2Games"
    sitemap_urls:
      - "https://2games.io/sitemap.xml"
    active: true
  - name: "8Games"
    sitemap_urls:
      - "https://8games.net/site-map.html?view=xml"
    active: true
  - name: "HotGames"
    sitemap_urls:
      - "https://hotgames.io/sitemap.xml"
    active: true
  - name: "OZGames"
    sitemap_urls:
      - "https://ozgames.io/sitemap.xml"
    active: true

high_traffic_sites:
  - name: "PolloAI"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true
  - name: "AIEaseAI"
    sitemap_urls:
      - "https://www.aiease.ai/sitemap-en.xml"
    active: true

nav_sites:
  - name: "AISearch"
    sitemap_urls:
      - "https://aishenqi.net/sitemap.xml"
    active: true


feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/01663cc7-52be-4a7a-828d-b54e143b4e5c"
  secret: "ZtyKHTHxmJwX7tY4Wkjdue"

storage:
  retention_days: 7
  data_dir: "./data"
