sites:
  - name: "PokeRogue"
    sitemap_urls:
      - "https://pokerogue.io/sitemap.xml"
    active: true
  - name: "Wordle2"
    sitemap_urls:
      - "https://wordle2.io/sitemap.xml"
    active: true
  - name: "1Games"
    sitemap_urls:
      - "https://1games.io/sitemap.xml"
    active: true
  - name: "AZGames"
    sitemap_urls:
      - "https://azgames.io/sitemap.xml"
    active: true
  - name: "CookieClicker2"
    sitemap_urls:
      - "https://cookie-clicker2.com/sitemap.xml"
    active: true
  - name: "Phrazle"
    sitemap_urls:
      - "https://phrazle.io/sitemap.xml"
    active: true
  - name: "Sprunki"
    sitemap_urls:
      - "https://sprunki.org/sitemap.xml"
    active: true
  - name: "ThatsNotMyNeighbor"
    sitemap_urls:
      - "https://thatsnot-myneighbor.io/sitemap.xml"
    active: true
  - name: "GeometryDashWave"
    sitemap_urls:
      - "https://geometrydashwave.io/sitemap.xml"
    active: true
  - name: "SmashyRoad"
    sitemap_urls:
      - "https://smashy-road.io/sitemap.xml"
    active: true
  - name: "GeometryDashIO"
    sitemap_urls:
      - "https://geometrylite.io/sitemap.xml"
    active: true
  - name: "PizzaEdition"
    sitemap_urls:
      - "https://pizzaedition.win/sitemap.xml"
    active: true
  - name: "EscapeRoad2"
    sitemap_urls:
      - "https://escaperoad2.io/sitemap.xml"
    active: true
  - name: "CoolMathGames"
    sitemap_urls:
      - "https://www.coolmathgames.com/sitemap.xml"
    active: true
  - name: "GameDistribution"
    sitemap_urls:
      - "https://gamedistribution.com/sitemap-index.xml"
    active: true
  - name: "CrazyGames"
    sitemap_urls:
      - "https://www.crazygames.com/sitemap-index.xml"
    active: true
  - name: "Poki"
    sitemap_urls:
      - "https://poki.com/en/sitemaps/index.xml"
    active: true
  - name: "TwoPlayerGames"
    sitemap_urls:
      - "https://www.twoplayergames.org/sitemap-games.xml"
    active: true
  - name: "OnlineGames"
    sitemap_urls:
      - "https://www.onlinegames.io/sitemap.xml"
    active: true
  - name: "MiniPlay"
    sitemap_urls:
      - "https://www.miniplay.com/sitemap.xml"
    active: true
  - name: "SayGames"
    sitemap_urls:
      - "https://say.games/sitemap.xml"
    active: true
  - name: "GameMonetize"
    sitemap_urls:
      - "https://gamemonetize.com/sitemap.xml"
    active: true
  - name: "GeometryLite"
    sitemap_urls:
      - "https://geometry-lite.io/sitemap.xml"
    active: true
  - name: "2Games"
    sitemap_urls:
      - "https://2games.io/sitemap.xml"
    active: true
  - name: "8Games"
    sitemap_urls:
      - "https://8games.net/site-map.html?view=xml"
    active: true
  - name: "HotGames"
    sitemap_urls:
      - "https://hotgames.io/sitemap.xml"
    active: true
  - name: "OZGames"
    sitemap_urls:
      - "https://ozgames.io/sitemap.xml"
    active: true

high_traffic_sites:
  - name: "PolloAI"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true
  - name: "AIEaseAI"
    sitemap_urls:
      - "https://www.aiease.ai/sitemap-en.xml"
    active: true

nav_sites:
  - name: "AISearch"
    sitemap_urls:
      - "https://aishenqi.net/sitemap.xml"
    active: true

back_link_sites:
  - name: "LaboParty"
    page_url: "https://labo-party.jp/hiroba/top.php?DIARY_ID&MENU=BBS&PAGE=suzue&W_ID=99211"
    target_domain: "labo-party.jp"
    active: true
  - name: "SorairoBBS"
    page_url: "https://sorairo.bbs.wox.cc/cate3.html?page=1"
    target_domain: "sorairo.bbs.wox.cc"
    active: true
  - name: "NaturalClean"
    page_url: "https://naturalclean.co.jp/blog6/blog.cgi/permalink/20200711051427"
    target_domain: "naturalclean.co.jp"
    active: true
  - name: "IndianJadibooti"
    page_url: "https://indianjadibooti.com/Jadistore/blog-headlines/Asafoetida-Hing-Cultivation-origin-quality-insights#c62591"
    target_domain: "indianjadibooti.com"
    active: true
  - name: "Ciskoreatown"
    page_url: "https://ciskoreatown.korean.net/bbs/board.php?bo_table=freeboard&page=1&sod=asc&sop=and&sst=wr_datetime&wr_id=5"
    target_domain: "ciskoreatown.korean.net"
    active: true
  - name: "PamMa"
    page_url: "https://pam.ma/fr/index.php/2025/01/09/el-mansouri-effectue-une-visite-de-terrain-et-signe-quatre-conventions-dans-le-cadre-de-la-politique-de-la-ville/"
    target_domain: "pam.ma"
    active: true
  - name: "Iubungei"
    page_url: "https://iubungei.cloud-line.com/iubungei/comment/2019/06/97653/"
    target_domain: "iubungei.cloud-line.com"
    active: true
  - name: "Fotosidan"
    page_url: "https://www.fotosidan.se/blogs/mittinrerum/sa-gick-det-till-nar-jag.htm#comments"
    target_domain: "fotosidan.se"
    active: true
  - name: "Spectral"
    page_url: "https://www.spectral.ro/Media/spectral-mobila-investeste-85-milioane-de-lei-intr-un-centru-logistic-din-judetul-vaslui-forbes-25-01-2024"
    target_domain: "spectral.ro"
    active: true
  - name: "WilliamsForum"
    page_url: "https://sites.williams.edu/thewilliamsforum/uncategorized/electability-identity-as-election-terms/attachment/cnn/"
    target_domain: "sites.williams.edu"
    active: true
  - name: "Bakerella"
    page_url: "https://www.bakerella.com/santas-bag-cake-pops/"
    target_domain: "bakerella.com"
    active: true
  - name: "UMBlogs"
    page_url: "https://blogs.umb.edu/jenniferpetruzzi001/2015/10/27/music-is-key/"
    target_domain: "blogs.umb.edu"
    active: true
  - name: "FitLivingEats"
    page_url: "https://www.fitlivingeats.com/qa-founders-motion-matcha-one-go-energy-boosters/"
    target_domain: "fitlivingeats.com"
    active: true
  - name: "SanitaPuglia"
    page_url: "https://edottosgd.sanita.puglia.it/knowledgetree/action.php?action=viewThread&fDocumentId=16801&fThreadId=2300&kt_path_info=ktcore.actions.document.discussion"
    target_domain: "edottosgd.sanita.puglia.it"
    active: true
  - name: "Alwihdainfo"
    page_url: "https://www.alwihdainfo.com/lonsikoko/Mortelle-surveillance_a153.html"
    target_domain: "alwihdainfo.com"
    active: true
  - name: "GodchildKeenspot"
    page_url: "http://godchild.keenspot.com/comic/chapter-3-page-05/"
    target_domain: "godchild.keenspot.com"
    active: true
  - name: "GermanistikaUnizd"
    page_url: "https://germanistika.unizd.hr/fotogalerija/emodule/25811/eitem/5042/userid/907"
    target_domain: "germanistika.unizd.hr"
    active: true
  - name: "BetterReading"
    page_url: "https://www.betterreading.com.au/news/book-life/wine-coffee-tea-what-do-you-drink-while-youre-reading/"
    target_domain: "betterreading.com.au"
    active: true
  - name: "InsuranceSplash"
    page_url: "https://www.insurancesplash.com/blog/insurance-sales-tips-for-new-insurance-agents"
    target_domain: "insurancesplash.com"
    active: true
  - name: "PrettyOpinionated"
    page_url: "https://www.prettyopinionated.com/2019/03/pharaoh-hound-dog-breed-guide/"
    target_domain: "prettyopinionated.com"
    active: true
  - name: "MatsubaraGensen"
    page_url: "https://www.matsubaragensen.com/hpgen/HPB/entries/12.html"
    target_domain: "matsubaragensen.com"
    active: true
  - name: "TheSigningStore"
    page_url: "https://thesigningstore.com/blog/best-beauty-products"
    target_domain: "thesigningstore.com"
    active: true
  - name: "TjednoHR"
    page_url: "https://www.tjedno.hr/poruke-za-milanovica-u-tisnom/comment-page-80/#comments"
    target_domain: "tjedno.hr"
    active: true
  - name: "TVWorthWatching"
    page_url: "http://www.tvworthwatching.com/post/Boardwalk-Rides.aspx"
    target_domain: "tvworthwatching.com"
    active: true
  - name: "UCLBritsBlog"
    page_url: "https://blogs.ucl.ac.uk/brits/2014/06/01/sales-growth-curves/"
    target_domain: "blogs.ucl.ac.uk"
    active: true
  - name: "MuseoTriora"
    page_url: "https://www.museotriora.it/2012/02/15/aa-vv-il-martirio-di-molini-e-triora-del-luglio-1944/"
    target_domain: "museotriora.it"
    active: true
  - name: "OceansConference"
    page_url: "https://global21.oceansconference.org/2019/04/01/join-5000-ocean-technology-experts-at-ocean-business/"
    target_domain: "global21.oceansconference.org"
    active: true
  - name: "GoNorthWales"
    page_url: "https://www.gonorthwales.co.uk/ideas-and-inspiration/blog/read/2016/07/10-facts-about-snowdonia-b31"
    target_domain: "gonorthwales.co.uk"
    active: true
  - name: "TirangaApps"
    page_url: "https://tirangaapps.com/top-7-tiranga-games/"
    target_domain: "tirangaapps.com"
    active: true
  - name: "DilettosoBBS"
    page_url: "https://dilettoso.cdx.jp/bbs/dilettoso_bbs.cgi?room=ohanashi&mode=sortnew&page=0&bl=0"
    target_domain: "dilettoso.cdx.jp"
    active: true
  - name: "HousingMapSG"
    page_url: "https://www.housingmap.sg/"
    target_domain: "housingmap.sg"
    active: true
  - name: "JoanieSimon"
    page_url: "https://joaniesimon.com/grilled-lemon-garlic-potato-kabobs/grilled-potato-kabobs-with-lemon-and-garlic/"
    target_domain: "joaniesimon.com"
    active: true
  - name: "SyncedReview"
    page_url: "https://syncedreview.com/2024/09/09/microsofts-fully-pipelined-distributed-transformer-processes-16x-sequence-length-with-extreme-hardware-efficiency/"
    target_domain: "syncedreview.com"
    active: true
  - name: "BeautyThroughImperfection"
    page_url: "https://www.beautythroughimperfection.com/reindeer-donuts/"
    target_domain: "beautythroughimperfection.com"
    active: true
  - name: "ManilaShopper"
    page_url: "https://www.manilashopper.com/2014/11/the-stoneware-pottery-shop-in-cagayan.html"
    target_domain: "manilashopper.com"
    active: true
  - name: "BrownEyedBaker"
    page_url: "https://www.browneyedbaker.com/how-to-make-pate-a-choux-fill-eclairs-and-cream-puffs/"
    target_domain: "browneyedbaker.com"
    active: true
  - name: "TechWinstonSalem"
    page_url: "http://tech.winstonsalem.com/2011/09/frameworks-becoming-totally-responsible.html"
    target_domain: "tech.winstonsalem.com"
    active: true


feishu:
  webhook_url: ""

storage:
  retention_days: 7
  data_dir: "./data"
